<?php

namespace Container9txNgIT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmployeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.r8eZeNu.App\Entity\Employe' shared service.
     *
     * @return \App\Entity\Employe
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.r8eZeNu": it references class "App\\Entity\\Employe" but no such service exists.');
    }
}
