<?php

namespace ContainerN0TIcav;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NU4qIpiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.NU4qIpi' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.NU4qIpi'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'departement' => ['privates', '.errored..service_locator.NU4qIpi.App\\Entity\\Departement', NULL, 'Cannot autowire service ".service_locator.NU4qIpi": it references class "App\\Entity\\Departement" but no such service exists.'],
        ], [
            'departement' => 'App\\Entity\\Departement',
        ]);
    }
}
