<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDNTN2D4\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDNTN2D4/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDNTN2D4.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDNTN2D4\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDNTN2D4\App_KernelDevDebugContainer([
    'container.build_hash' => 'DNTN2D4',
    'container.build_id' => 'bbc557fc',
    'container.build_time' => 1672563945,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDNTN2D4');
